import { auth, RecaptchaVerifier, signInWithPhoneNumber, onAuthStateChanged } from "./firebase.js";
const chats=[{id:1,name:"Aarav",msg:"Hey! How are you?",time:"12:42",status:"online",fav:true,unread:2,avatar:"A"},{id:2,name:"Family Group",msg:"Mom: Dinner at 8 🍲",time:"11:05",status:"4 members online",fav:true,unread:0,avatar:"F"},{id:3,name:"Riya",msg:"Photo 📷",time:"Yesterday",status:"last seen today at 10:21",fav:false,unread:1,avatar:"R"},{id:4,name:"School Group",msg:"Math homework reminder",time:"Yesterday",status:"18 members",fav:false,unread:0,avatar:"S"}];let current=null,tab="chats",filter="all";const $=x=>document.getElementById(x),main=$("main"),conv=$("conversation"),list=$("tabContent"),search=$("search"),messages=$("messages"),input=$("input"),toast=$("toast");let store=JSON.parse(localStorage.getItem("connectchat-v3")||"{}");
function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function render(){if(tab!=="chats"){renderPanel();return}let q=search.value.toLowerCase();let data=chats.filter(c=>(c.name+c.msg).toLowerCase().includes(q));if(filter==="unread")data=data.filter(c=>c.unread);if(filter==="favs")data=data.filter(c=>c.fav);list.innerHTML=data.map(c=>'<div class="chat-item '+(current?.id===c.id?"active":"")+'" data-id="'+c.id+'"><div class="avatar">'+c.avatar+'</div><div class="meta"><strong>'+esc(c.name)+'</strong><p>'+esc(c.msg)+'</p></div><div class="chat-right">'+c.time+(c.unread?'<div class="badge">'+c.unread+'</div>':'')+'</div></div>').join("")||'<div class="panel">No chats found</div>';document.querySelectorAll(".chat-item").forEach(x=>x.onclick=()=>openChat(+x.dataset.id))}
function renderPanel(){search.style.display="none";document.querySelector(".filter-row").style.display="none";let title=tab==="updates"?"Updates":tab==="communities"?"Communities":"Calls";let body=tab==="updates"?'<div class="panel-row"><div class="big">◉</div><div><b>My status</b><p>Tap to add a status update</p></div></div><div class="panel-row"><div class="big">◉</div><div><b>Recent updates</b><p>No new updates</p></div></div>':tab==="communities"?'<div class="panel-row"><div class="big">⌘</div><div><b>New community</b><p>Create a community for groups and announcements</p></div></div><div class="panel-row"><div class="big">👥</div><div><b>School Community</b><p>Announcements and groups</p></div></div>':'<div class="panel-row"><div class="big">＋</div><div><b>Create call link</b><p>Share a link for a call</p></div></div><div class="panel-row"><div class="big">☎</div><div><b>Recent calls</b><p>No recent calls</p></div></div>';list.innerHTML='<div class="panel"><h2>'+title+'</h2>'+body+'</div>'}
function openChat(id){current=chats.find(c=>c.id===id);current.unread=0;conv.classList.remove("hidden");main.classList.add("show");$("name").textContent=current.name;$("status").textContent=current.status;$("avatar").textContent=current.avatar;renderMessages();render()}
function renderMessages(){let base=[{t:"Hi! Welcome to ConnectChat 👋",o:false,tm:"12:38"},{t:current.msg,o:false,tm:current.time}];let a=store[current.id]||base;messages.innerHTML=a.map(m=>'<div class="msg '+(m.o?"out":"in")+'"><span>'+esc(m.t)+'</span><time>'+m.tm+(m.o?'<span class="ticks">✓✓</span>':"")+'</time></div>').join("");messages.scrollTop=messages.scrollHeight}
function notify(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1600)}
$("composer").onsubmit=e=>{e.preventDefault();let t=input.value.trim();if(!t||!current)return;let a=store[current.id]||[{t:"Hi! Welcome to ConnectChat 👋",o:false,tm:"12:38"}];a.push({t,o:true,tm:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})});store[current.id]=a;localStorage.setItem("connectchat-v3",JSON.stringify(store));input.value="";renderMessages()};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");search.style.display=tab==="chats"?"flex":"none";document.querySelector(".filter-row").style.display=tab==="chats"?"flex":"none";render()});
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});search.oninput=render;
$("back").onclick=()=>main.classList.remove("show");$("emoji").onclick=()=>$("emojiBar").classList.toggle("hidden");$("emojiBar").onclick=e=>{input.value+=e.target.textContent;input.focus()};$("attach").onclick=()=>notify("Attachments will be connected to storage later.");$("newChat").onclick=()=>notify("New chat is ready for the accounts backend.");$("camera").onclick=()=>notify("Camera UI coming with the Android build.");$("menu").onclick=()=>notify("Settings menu coming next.");$("call").onclick=()=>notify("Calling requires the backend.");$("video").onclick=()=>notify("Video calling requires the backend.");$("chatMenu").onclick=()=>notify("Chat options");render();
let confirmationResult=null, recaptchaVerifier=null;
const authScreen=document.getElementById("authScreen"), phoneStep=document.getElementById("phoneStep"), otpStep=document.getElementById("otpStep"), phoneNumber=document.getElementById("phoneNumber"), otpCode=document.getElementById("otpCode"), authError=document.getElementById("authError");
function setAuthError(msg){authError.textContent=msg}
function setupRecaptcha(){if(recaptchaVerifier)return;recaptchaVerifier=new RecaptchaVerifier(auth,"sendOtp",{size:"invisible",callback:()=>{}});recaptchaVerifier.render().catch(()=>{})}
function sendOtp(){const n=phoneNumber.value.replace(/\D/g,"");if(n.length!==10){setAuthError("Enter a valid 10-digit mobile number.");return}setAuthError("");setupRecaptcha();signInWithPhoneNumber(auth,"+91"+n,recaptchaVerifier).then(r=>{confirmationResult=r;phoneStep.classList.add("hidden");otpStep.classList.remove("hidden");document.getElementById("authTitle").textContent="Verify your mobile number"}).catch(e=>{setAuthError(e.message||"Could not send OTP.");try{recaptchaVerifier.clear()}catch{}recaptchaVerifier=null})}
document.getElementById("sendOtp").onclick=sendOtp;
document.getElementById("verifyOtp").onclick=()=>{const code=otpCode.value.trim();if(!confirmationResult){setAuthError("Please request an OTP first.");return}if(!/^\d{6}$/.test(code)){setAuthError("Enter the 6-digit OTP.");return}setAuthError("");confirmationResult.confirm(code).then(()=>{authScreen.classList.add("hidden")}).catch(()=>setAuthError("Incorrect or expired OTP."))};
document.getElementById("changeNumber").onclick=()=>{confirmationResult=null;otpStep.classList.add("hidden");phoneStep.classList.remove("hidden");document.getElementById("authTitle").textContent="Enter your mobile number";setAuthError("")};
onAuthStateChanged(auth,user=>{if(user){authScreen.classList.add("hidden")}else{authScreen.classList.remove("hidden")}});
