const chats=[{id:1,name:"Aarav",msg:"Hey! How are you?",time:"12:42",status:"online",fav:true,unread:2,avatar:"A"},{id:2,name:"Family Group",msg:"Mom: Dinner at 8 🍲",time:"11:05",status:"4 members online",fav:true,unread:0,avatar:"F"},{id:3,name:"Riya",msg:"Photo 📷",time:"Yesterday",status:"last seen today at 10:21",fav:false,unread:1,avatar:"R"},{id:4,name:"School Group",msg:"Math homework reminder",time:"Yesterday",status:"18 members",fav:false,unread:0,avatar:"S"}];
let current=null,filter="all";const $=id=>document.getElementById(id),list=$("list"),search=$("search"),main=$("main"),empty=$("empty"),chat=$("chat"),nameEl=$("name"),statusEl=$("status"),avatar=$("avatar"),messages=$("messages"),form=$("form"),input=$("input"),emojiBar=$("emojiBar"),toast=$("toast");let store=JSON.parse(localStorage.getItem("connectchat-v2")||"{}");
function render(){const q=search.value.toLowerCase();let data=chats.filter(c=>(c.name+c.msg).toLowerCase().includes(q));if(filter==="unread")data=data.filter(c=>c.unread);if(filter==="fav")data=data.filter(c=>c.fav);list.innerHTML=data.map(c=>'<div class="chat-item '+(current?.id===c.id?"active":"")+'" data-id="'+c.id+'"><div class="avatar small">'+c.avatar+'</div><div class="chat-meta"><strong>'+escapeHtml(c.name)+'</strong><p>'+escapeHtml(c.msg)+'</p></div><div><div class="time">'+c.time+'</div>'+(c.unread?'<div class="badge">'+c.unread+'</div>':'')+'</div></div>').join("")||'<div style="padding:30px;text-align:center;color:#667781">No chats found</div>';document.querySelectorAll(".chat-item").forEach(x=>x.onclick=()=>openChat(+x.dataset.id))}
function openChat(id){current=chats.find(c=>c.id===id);current.unread=0;empty.classList.add("hidden");chat.classList.remove("hidden");main.classList.add("show");nameEl.textContent=current.name;statusEl.textContent=current.status;avatar.textContent=current.avatar;renderMessages();render()}
function renderMessages(){const base=[{t:"Hi! Welcome to ConnectChat 👋",o:false,tm:"12:38"},{t:current.msg,o:false,tm:current.time}];const msgs=store[current.id]||base;messages.innerHTML=msgs.map(m=>'<div class="msg '+(m.o?"out":"in")+'"><span>'+escapeHtml(m.t)+'</span><time>'+m.tm+(m.o?'<span class="ticks">✓✓</span>':"")+'</time></div>').join("");messages.scrollTop=messages.scrollHeight}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function showToast(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}
form.onsubmit=e=>{e.preventDefault();const t=input.value.trim();if(!t||!current)return;const msgs=store[current.id]||[{t:"Hi! Welcome to ConnectChat 👋",o:false,tm:"12:38"}];msgs.push({t,o:true,tm:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})});store[current.id]=msgs;localStorage.setItem("connectchat-v2",JSON.stringify(store));input.value="";emojiBar.classList.add("hidden");renderMessages()};
search.oninput=render;document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{filter=b.dataset.f;document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});
$("back").onclick=()=>main.classList.remove("show");$("emoji").onclick=()=>emojiBar.classList.toggle("hidden");emojiBar.onclick=e=>{if(e.target!==emojiBar){input.value+=e.target.textContent;input.focus()}else{input.value+=e.target.textContent;input.focus()}};$("attach").onclick=()=>showToast("Attachments will be enabled with the backend.");$("newChat").onclick=()=>showToast("New-chat contacts will be enabled with accounts.");$("menuBtn").onclick=()=>showToast("Settings coming with the next backend step.");$("chatMenu").onclick=()=>showToast("Chat options");render();